### PR TITLE
fixed cd printing path when not needed

### LINKED ISSUE #21: ft_free_env_list does not free last item
```
==634== 31 (24 direct, 7 indirect) bytes in 1 blocks are definitely lost in loss record 2 of 2
==634==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==634==    by 0x10BB64: ft_memalloc (ft_memalloc.c:19)
==634==    by 0x109730: ft_addenv (ft_setenv.c:36)
==634==    by 0x109880: ft_setenv (ft_setenv.c:71)
==634==    by 0x10AAF3: ft_cd_builtin (ft_cd_builtin.c:54)
==634==    by 0x109E68: execute_builtin (ft_handle_command.c:48)
==634==    by 0x109FF5: ft_handle_command (ft_handle_command.c:75)
==634==    by 0x1092EE: input_loop (main.c:36)
==634==    by 0x10937B: main (main.c:56)
```

### LINKED ISSUE #22: OLDPWD is not set env cd'ing with an empty environment
```
 -ish » env
LD_PRELOAD=/usr/lib/valgrind/vgpreload_core-amd64-linux.so:/usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
STATUS_CODE=0
 -ish » cd incl
incl
-ish: Environment key not found
-ish: Failure to allocate memory
 -ish » env
LD_PRELOAD=/usr/lib/valgrind/vgpreload_core-amd64-linux.so:/usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
STATUS_CODE=0
PWD=/pwd/incl
 -ish » cd -
-ish: Environment key not found
-ish: Environment key not found
-ish: Failure to allocate memory
 -ish » /bin/pwd
/pwd/incl
```

### LINKED ISSUE #25: cd always prints destentation
According to the standard, cd should print the destination when using `cd -`:

> OPERANDS
> 
> The following operands shall be supported:
> 
> **directory**
> An absolute or relative pathname of the directory that shall become the new working directory. The interpretation of a relative pathname by cd depends on the -L option and the CDPATH and PWD environment variables. If directory is an empty string, the results are unspecified.
> **-**
> When a <hyphen-minus> is used as the operand, this shall be equivalent to the command:
> 
> `cd "$OLDPWD" && pwd`
> 
> which changes to the previous working directory and then writes its name.

The current implementation always prints the destination.

### PR DESCRIPTION
**Pull request by lgutter**
cd will now only print the path it's trying to change to,
if the argument is -.
Also removed the error print from getenv since it wasn't really useful anywhere.

closes #25 
closes #22 
closes #21

### CODE REVIEW

File: srcs/ft_cd_builtin.c [hunk 1]
```diff
@@ -36,12 +42,15 @@ static char	*find_path(t_env *env_list, t_command *command)
...
+	char	*old_path;
 	int		ret;
 
 	ret = 0;
 	path = find_path(env_list, command);
 	if (path == NULL)
-		return (ft_print_error(ERR_MALLOCFAIL));
+		return (ERR_ENVNOTFOUND);
+	old_path = NULL;
+	old_path = getcwd(old_path, 0);
```
Comment (nloomans) [inline srcs/ft_cd_builtin.c]: Why not `old_path = getcwd(NULL, 0);`

Comment (lgutter) [reply srcs/ft_cd_builtin.c]: Good point, added to PR.
